version: "3"
services:
  terraform:
    container_name: "terraform"
    image: hashicorp/terraform:latest
    tty: true
    working_dir: /infra/terraform
    env_file:
      - .env
    volumes:
      - ./src:/infra/terraform
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./go:/go/src/app
